title: Simple Website Demo
email: "NA"
description: "NA"
baseurl: "/websitedraft" 
url: "https://joebd.github.io"
github_username: joebd

permalink: pretty
search_enabled: false
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

  
  
