title: "Simple Webpage Demo" 
description: "Home" 
email: "NA" 
remote_theme: just-the-docs/just-the-docs
color: dark
permalink: pretty
search_enabled: false
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"
