title: Simple Website Demo
email: "NA"
description: "test"
baseurl: "/websitedraft" 
url: "https://joebd.github.io"
github_username: joebd

permalink: pretty
search_enabled: false
enable_copy_code_button: true
back_to_top: true
back_to_top_text: "Back to top"

exclude: 
  - README.md
  - home.md

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

ga_tracking: # id
ga_tracking_anonymize_ip:  # Use GDPR compliant Google Analytics settings (true/nil by default)
  
